"use client";
import type { Metadata } from "next";

import "./globals.css";

import { Poppins } from "next/font/google";

import "./globals.css";
import Aos from "aos";
import { useEffect } from "react";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    Aos.init();
  }, []);
  return (
    <html lang="en">
      <body className={`${poppins.className} dark antialiased`}>
        {children}
      </body>
    </html>
  );
}
